services:
  db:
    container_name: dreamshops
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: wamiti
      POSTGRES_PASSWORD: Wamiti@55
      POSTGRES_DB: dreamshops
      PGDATA: /var/lib/postgresql/data
    volumes:
      - dreamshops_db_data:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - dreamshops_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wamiti -d dreamshops"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dreamshops_network:
    driver: bridge

volumes:
  dreamshops_db_data:
