spring:
  application:
    name: dream-shops
  config:
    import: "file:keys.properties"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  
  # Redis Configuration
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port:6379}
      password: ${redis.password}
      database: ${redis.database}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      ssl:
        enabled: false
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000 
      cache-null-values: false
      use-key-prefix: true
      key-prefix: dream-shops
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope: openid,profile,email
            redirect-uri: ${google.redirect.uri}
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8085
  servlet:
    context-path: /

firebase:
  bucket-name: ${firebase.bucket.name}
  credentials:
    path: service-account.json

app:
  jwtSecret: ${jwt.secret}
  jwtExpirationMs: ${jwt.expiration.ms}
  jwtRefreshExpirationMs: ${jwt.refresh.expiration.ms}
  oauth2:
    authorizedRedirectUri: ${oauth2.authorized.redirect.uri}

    mobileRedirectUri: ${oauth2.mobile.redirect.uri}
    webRedirectUri: ${oauth2.web.redirect.uri}
    # Fallback custom scheme for mobile
    mobileCustomSchemeUri: ${oauth2.mobile.custom.scheme.uri}
  cache:
    ttl:
      products: 600 
      categories: 1800
      users: 300 

api:
  prefix: api/v1

logging:
  level:
    com.newton.dream_shops.security.oauth: DEBUG
    com.newton.dream_shops.services.auth: DEBUG
    com.newton.dream_shops.cache: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.security: DEBUG